name: Rebase
on:
  # schedule:
  #   - cron:  '40 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rebase:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: peter-evans/rebase@87c3fd9344792e51ab1c7494c3369620c84ed852 # v3.1.0
        with:
          token: ${{ secrets.GH_PAT }}
          exclude-labels: |
            no-rebase
            dependencies
          # exclude-drafts: true
